# name: "Cleanup Action"
# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 1 * * 1" # Runs every Monday at 2:00 AM UTC
    
jobs:
  ghcr-cleanup:
    name: ghcr.io cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          dry-run: true
          package: dataengine
          delete-untagged: true
          exclude-tags: v**
          older-than: 30 days
