name: "Cleanup Action"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1" # Runs every Monday at 2:00 AM UTC
    
jobs:
  ghcr-cleanup:
    name: ghcr.io cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: true
          exclude-tags: v**, rc-release**, hotfix**
          delete-untagged: true
          older-than: 90 days